force-app/main/default/objects/Case/fields/ExternalCaseId__c.field-meta.xml
<CustomField>
    <fullName>ExternalCaseId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Case Id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ProductComplaintResponseEvent__e/ProductComplaintResponseEvent__e.object-meta.xml
<CustomObject>
    <label>Product Complaint Response Event</label>
    <pluralLabel>Product Complaint Response Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/ProductComplaintResponseEvent__e/fields/CaseId__c.field-meta.xml
<CustomField>
    <fullName>CaseId__c</fullName>
    <description>External System Case Id</description>
    <label>CaseId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductComplaintResponseEvent__e/fields/TrackingId__c.field-meta.xml
<CustomField>
    <fullName>TrackingId__c</fullName>
    <label>Tracking Id</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ProductComplaint/triggers/ProductComplaintResponseEvent_UpdateCase.cls
public class ProductComplaintResponseEvent_UpdateCase implements TriggerAction.AfterInsert {
    public void afterInsert(List<ProductComplaintResponseEvent__e> newList){
        Set<Id> caseIds = new Set<Id>();
        for (ProductComplaintResponseEvent__e event : newList) {
            if (event.TrackingId__c != null) {
                caseIds.add(event.TrackingId__c);
            }
        }

        Map<Id, Case> casesToUpdate = new Map<Id, Case>([
            SELECT ExternalCaseId__c
            FROM Case
            WHERE Id IN :caseIds
        ]);

        for (ProductComplaintResponseEvent__e event : newList) {
            if (casesToUpdate.containsKey(event.TrackingId__c)) {
                Case caseUpdate = casesToUpdate.get(event.TrackingId__c);
                caseUpdate.ExternalCaseId__c = event.CaseId__c;
            }
        }

        update casesToUpdate.values();
    }
}