force-app/main/default/objects/ProductComplaintResponseEvent__e/ProductComplaintResponseEvent__e.object-meta.xml
<CustomObject>
    <label>Product Complaint Response Event</label>
    <pluralLabel>Product Complaint Response Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/ProductComplaintResponseEvent__e/fields/CaseId__c.field-meta.xml
<CustomField>
    <fullName>CaseId__c</fullName>
    <description>External System Case Id</description>
    <label>CaseId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductComplaintResponseEvent__e/fields/TrackingId__c.field-meta.xml
<CustomField>
    <fullName>TrackingId__c</fullName>
    <label>Tracking Id</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Utils/Builders/Tests/BaseProductComplaintResponseTestBuilder.cls
public virtual class BaseProductComplaintResponseTestBuilder extends TestDataBuilder {
    public BaseProductComplaintResponseTestBuilder() {
        record = new ProductComplaintResponseEvent__e();
    }

    protected virtual override void prepare(){
        ProductComplaintResponseEvent__e event = (ProductComplaintResponseEvent__e) record;
        if (String.isBlank(event.CaseId__c)) {
            event.CaseId__c = 'TestExternalCase';
        }
    }

    public BaseProductComplaintResponseTestBuilder withTrackingId(String trackingId) {
        ProductComplaintResponseEvent__e event = (ProductComplaintResponseEvent__e) record;
        event.TrackingId__c = trackingId;
        return this;
    }
}