force-app/main/default/objects/ComplaintItemCompleted__e/ComplaintItemCompleted__e.object-meta.xml
<CustomObject>
    <label>Complaint Item Completed</label>
    <pluralLabel>Complaint Items Completed</pluralLabel>
</CustomObject>

force-app/main/default/objects/ComplaintItemCompleted__e/fields/ComplaintItems__c.field-meta.xml
<CustomField>
    <fullName>ComplaintItems__c</fullName>
    <label>Complaint Items</label>
    <length>65536</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/Utils/Builders/Tests/BaseComplaintItemCompletedTestBuilder.cls
public class BaseComplaintItemCompletedTestBuilder extends TestDataBuilder {
    public BaseComplaintItemCompletedTestBuilder() {
        record = new ComplaintItemCompleted__e();
    }

    public BaseComplaintItemCompletedTestBuilder withComplaintItems(String complaintItems) {
        ComplaintItemCompleted__e event = (ComplaintItemCompleted__e) record;
        event.ComplaintItems__c = complaintItems;
        return this;
    }
}