force-app/main/default/objects/Discount_Strategy_Setting__mdt/Discount_Strategy_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Discount Strategy Setting</label>
    <pluralLabel>Discount_Strategy_Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Discount_Strategy_Setting__mdt/fields/Maximum_Discount__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Discount__c</fullName>
    <description>Maximum total discount per order</description>
    <label>Maximum Discount</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Discount_Strategy_Setting__mdt/fields/Strategy__c.field-meta.xml
<CustomField>
    <fullName>Strategy__c</fullName>
    <label>Strategy</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Highest</fullName>
                <default>true</default>
                <label>Highest</label>
            </value>
            <value>
                <fullName>Lowest</fullName>
            </value>
            <value>
                <fullName>Combined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RequestLogSetting__mdt/RequestLogSetting__mdt.object-meta.xml
<CustomObject>
    <label>Request Log Setting</label>
    <pluralLabel>Request Log Setting</pluralLabel>
</CustomObject>

force-app/main/default/objects/RequestLogSetting__mdt/fields/MaxAttemptNumber__c.field-meta.xml
<CustomField>
    <fullName>MaxAttemptNumber__c</fullName>
    <description>How many times a request should be resend after failure</description>
    <label>Max Attempt Number</label>
    <precision>1</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RequestLogSetting__mdt/fields/MaxProductsPerRequest__c.field-meta.xml
<CustomField>
    <fullName>MaxProductsPerRequest__c</fullName>
    <description>Limit of product records in a single request</description>
    <label>Max Products Per Request</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RequestLogSetting__mdt/fields/MaxRequestsPerBatch__c.field-meta.xml
<CustomField>
    <fullName>MaxRequestsPerBatch__c</fullName>
    <description>How many request should be send in a single batch</description>
    <label>Max Requests Per Batch</label>
    <precision>1</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Utils/Constants/Constants.cls
public class Constants {
    
    public static Id STANDARD_PRICEBOOK_ID {
        get {
            if (STANDARD_PRICEBOOK_ID == null) {
                STANDARD_PRICEBOOK_ID = [SELECT Id FROM Pricebook2 WHERE IsStandard = true LIMIT 1].Id;
            }
            return STANDARD_PRICEBOOK_ID;
        }
        private set;
    }

    public static Discount_Strategy_Setting__mdt DISCOUNT_STRATEGY_SETTING {
        get {
            if (DISCOUNT_STRATEGY_SETTING == null) {
                DISCOUNT_STRATEGY_SETTING = [SELECT Maximum_Discount__c, Strategy__c FROM Discount_Strategy_Setting__mdt LIMIT 1];
            }
            return DISCOUNT_STRATEGY_SETTING;
        }
        private set;
    }

    public static RequestLogSetting__mdt REQUEST_LOG_SETTING {
        get {
            if (REQUEST_LOG_SETTING == null) {
                List<RequestLogSetting__mdt> settings = [SELECT MaxAttemptNumber__c, MaxProductsPerRequest__c, MaxRequestsPerBatch__c FROM RequestLogSetting__mdt LIMIT 1];
                if (settings.size() > 0) {
                    REQUEST_LOG_SETTING = settings[0];
                } else {
                    return new RequestLogSetting__mdt(
                        MaxAttemptNumber__c = 3,
                        MaxProductsPerRequest__c = 50,
                        MaxRequestsPerBatch__c = 1
                    );
                }
            }
            return REQUEST_LOG_SETTING;
        }
        private set;
    }

    public static final String PRODUCT_SYNC_API_ENDPOINT { 
        get { 
            return 'callout:External_Data_Org/services/apexrest/Product/sync/';
        }
    }

    public static final String EXTERNAL_COMPLAINT_EVENT_API_ENDPOINT {
        get {
            return 'callout:External_Data_Org/services/data/v62.0/sobjects/ProductComplaintEvent__e/';
        }
    }

    public static final AccountConstants Account {
        get {
            return new AccountConstants();
        }
    }

    public static final OrderConstants Order {
        get {
            return new OrderConstants();
        }
    }

    public static final ProductConstants Product {
        get {
            return new ProductConstants();
        }
    }

    public static final DiscountConstants Discount {
        get {
            return new DiscountConstants();
        }
    }

    public static final ContractConstants Contract {
        get {
            return new ContractConstants();
        }
    }

    public static final OpportunityConstants Opportunity {
        get {
            return new OpportunityConstants();
        }
    }

    public static final RESTConstants RestAPI {
        get {
            return new RESTConstants();
        }
    }

    public static final RequestLogConstants RequestLog {
        get {
            return new RequestLogConstants();
        }
    }
}