force-app/main/default/objects/Discount_Strategy_Setting__mdt/Discount_Strategy_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Discount Strategy Setting</label>
    <pluralLabel>Discount_Strategy_Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Discount_Strategy_Setting__mdt/fields/Maximum_Discount__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Discount__c</fullName>
    <description>Maximum total discount per order</description>
    <label>Maximum Discount</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Discount_Strategy_Setting__mdt/fields/Strategy__c.field-meta.xml
<CustomField>
    <fullName>Strategy__c</fullName>
    <label>Strategy</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Highest</fullName>
                <default>true</default>
                <label>Highest</label>
            </value>
            <value>
                <fullName>Lowest</fullName>
            </value>
            <value>
                <fullName>Combined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Discounts/tests/DiscountTestingSettings.cls
@isTest
public class DiscountTestingSettings {
    public static Discount_Strategy_Setting__mdt setting {
        get {
            if(setting == null) {
                setting = new Discount_Strategy_Setting__mdt(
                    Maximum_Discount__c = 35,
                    Strategy__c = Constants.Discount.STRATEGY_HIGHEST
                );
            }
            return setting;
        }
        set {
            setting = value;
        }
    }
}