force-app/main/default/objects/OrderDiscount__c/OrderDiscount__c.object-meta.xml
<CustomObject>
    <label>OrderDiscount</label>
    <nameField>
        <label>Order Discount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OrderDiscounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderDiscount__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <label>Discount</label>
    <referenceTo>Discount__c</referenceTo>
    <relationshipLabel>OrderDiscounts</relationshipLabel>
    <relationshipName>OrderDiscounts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OrderDiscount__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>OrderDiscounts</relationshipLabel>
    <relationshipName>OrderDiscounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Utils/Builders/Tests/BaseOrderDiscountTestDataBuilder.cls
public virtual class BaseOrderDiscountTestDataBuilder extends TestDataBuilder {
    public BaseOrderDiscountTestDataBuilder() {
        record = new OrderDiscount__c();
    }
    
    protected virtual override void prepare(){
        OrderDiscount__c orderDiscount = (OrderDiscount__c) record;
        if (String.isBlank(orderDiscount.Name)) {
            orderDiscount.Name = 'Test Order Discount';
        }
    }

    public BaseOrderDiscountTestDataBuilder withOrder(Order order) {
        OrderDiscount__c orderDiscount = (OrderDiscount__c) record;
        orderDiscount.Order__c = order.Id;
        return this;
    }

    public BaseOrderDiscountTestDataBuilder withDiscount(Discount__c discount) {
        OrderDiscount__c orderDiscount = (OrderDiscount__c) record;
        orderDiscount.Discount__c = discount.Id;
        return this;
    }
}