force-app/main/default/objects/OrderDiscount__c/OrderDiscount__c.object-meta.xml
<CustomObject>
    <label>OrderDiscount</label>
    <nameField>
        <label>Order Discount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OrderDiscounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderDiscount__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <label>Discount</label>
    <referenceTo>Discount__c</referenceTo>
    <relationshipLabel>OrderDiscounts</relationshipLabel>
    <relationshipName>OrderDiscounts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OrderDiscount__c/fields/Discount_Amount__c.field-meta.xml
<CustomField>
    <fullName>Discount_Amount__c</fullName>
    <description>A discount value specific for the order. If multiple discounts in an order hit discount limit this value might be 0.</description>
    <label>Discount Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderDiscount__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>OrderDiscounts</relationshipLabel>
    <relationshipName>OrderDiscounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Discounts/triggers/OrderItem_RecreateDiscounts.cls
public class OrderItem_RecreateDiscounts implements TriggerAction.AfterUpdate, TriggerAction.AfterInsert, TriggerAction.AfterDelete{
    
    public void afterUpdate(List<OrderItem> newList, List<OrderItem> oldList){
        recreateDisconts(newList);
    }

    public void afterInsert(List<OrderItem> newList){
        recreateDisconts(newList);
    }

    public void afterDelete(List<OrderItem> oldList){
        recreateDisconts(oldList);
    }

    private static void recreateDisconts(List<OrderItem> orderItems){
        Set<Id> orderIds = new Set<Id>();
        for(OrderItem item : orderItems){
            if(item.OrderId != null){
                orderIds.add(item.OrderId);
            }
        }
        recreateDisconts(orderIds);
    }
    
    private static void recreateDisconts(Set<Id> orderIds){
        Map<Id, List<OrderItem>> orderIdToItems = getOrderIdToItems(orderIds);
        Map<Id, Id> orderIdToPricebookId = getOrderIdToPricebookId(orderIds);
        Map<Id, List<OrderItemsDiscountEvaluator.ItemDiscountResult>> orderIdToDiscounts = getOrderIdToDiscounts(orderIdToItems, orderIdToPricebookId);

        delete [SELECT Id FROM OrderDiscount__c WHERE Order__c IN :orderIds];
        
        List<OrderDiscount__c> discountsToInsert = new List<OrderDiscount__c>();
        for (Id orderId : orderIdToDiscounts.keySet()) {
            for (OrderItemsDiscountEvaluator.ItemDiscountResult itemDiscounts : orderIdToDiscounts.get(orderId)) {
                discountsToInsert.addAll(generateOrderDiscounts(itemDiscounts.appliedDiscounts, orderId));
            }
        }
        insert discountsToInsert;
    }

    private static Map<Id, List<OrderItem>> getOrderIdToItems(Set<Id> orderIds) {
        Map<Id, List<OrderItem>> orderIdToItems = new Map<Id, List<OrderItem>>();
        for (orderItem item : [SELECT OrderId, Quantity, UnitPrice, Product2Id FROM OrderItem WHERE OrderId IN :orderIds]) {
            if (!orderIdToItems.containsKey(item.OrderId)) {
                orderIdToItems.put(item.OrderId, new List<OrderItem>());
            }
            orderIdToItems.get(item.OrderId).add(item);
        }
        return orderIdToItems;
    }

    private static Map<Id, Id> getOrderIdToPricebookId(Set<Id> orderIds) {
        Map<Id, Id> orderIdToPricebookId = new Map<Id, Id>();
        for (Order order : [SELECT Id, Pricebook2Id FROM Order WHERE Id IN :orderIds]) {
            if (order.Pricebook2Id != null) {
                orderIdToPricebookId.put(order.Id, order.Pricebook2Id);
            } else {
                orderIdToPricebookId.put(order.Id, Constants.STANDARD_PRICEBOOK_ID);
            }
        }
        return orderIdToPricebookId;
    }

    private static Map<Id, List<OrderItemsDiscountEvaluator.ItemDiscountResult>> getOrderIdToDiscounts(Map<Id, List<OrderItem>> orderIdToItems, Map<Id, Id> orderIdToPricebookId) {
        Map<Id, List<OrderItemsDiscountEvaluator.ItemDiscountResult>> orderIdToDiscounts = new Map<Id, List<OrderItemsDiscountEvaluator.ItemDiscountResult>>();
        for (Id orderId : orderIdToItems.keySet()) {
            List<OrderItemsDiscountEvaluator.ItemDiscountResult> discounts = OrderItemsDiscountEvaluator.evaluate(orderIdToItems.get(orderId), orderIdToPricebookId.get(orderId));
            if (discounts != null && !discounts.isEmpty()) {
                orderIdToDiscounts.put(orderId, discounts);
            }
        }
        return orderIdToDiscounts;
    }

    private static List<OrderDiscount__c> generateOrderDiscounts(List<ItemDiscountEvaluator.EvaluatedDiscount> evaluatedDiscounts, Id orderId) {
        List<OrderDiscount__c> discounts = new List<OrderDiscount__c>();
        for (ItemDiscountEvaluator.EvaluatedDiscount evaluatedDiscount : evaluatedDiscounts) {
            OrderDiscount__c orderDiscount = new OrderDiscount__c();
            orderDiscount.Order__c = orderId;
            orderDiscount.Discount__c = evaluatedDiscount.discount.Id;
            orderDiscount.Discount_Amount__c = evaluatedDiscount.discountAmount;
            orderDiscount.Name = evaluatedDiscount.discount.Name;
            discounts.add(orderDiscount);
        }
        return discounts;
    }
}