force-app/main/default/objects/ComplaintItem__c/ComplaintItem__c.object-meta.xml
<CustomObject>
    <label>Complaint Item</label>
    <nameField>
        <label>Complaint Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Complaint Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ComplaintItem__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Complaint Items</relationshipLabel>
    <relationshipName>Complaint_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ComplaintItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Complaint Items</relationshipLabel>
    <relationshipName>Complaint_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Utils/Builders/Tests/BaseComplaintItemTestDataBuilder.cls
public virtual class BaseComplaintItemTestDataBuilder extends TestDataBuilder {
    public BaseComplaintItemTestDataBuilder() {
        record = new ComplaintItem__c();
    }
    
    protected virtual override void prepare(){
        ComplaintItem__c complaint = (ComplaintItem__c) record;
        if (complaint.UnitPrice__c == null) {
            complaint.UnitPrice__c = 100;
        }
        if (complaint.Quantity__c == null) {
            complaint.Quantity__c = 1;
        }
    }

    public BaseComplaintItemTestDataBuilder withProduct(Product2 product) {
        ComplaintItem__c complaint = (ComplaintItem__c) record;
        complaint.Product__c = product.Id;
        return this;
    }

    public BaseComplaintItemTestDataBuilder withCase(Case caseRecord) {
        ComplaintItem__c complaintItem = (ComplaintItem__c) record;
        complaintItem.Case__c = caseRecord.Id;
        return this;
    }
}