force-app/main/default/objects/ComplaintItem__c/ComplaintItem__c.object-meta.xml
<CustomObject>
    <label>Complaint Item</label>
    <nameField>
        <label>Complaint Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Complaint Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ComplaintItem__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Complaint Items</relationshipLabel>
    <relationshipName>Complaint_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ComplaintItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Complaint Items</relationshipLabel>
    <relationshipName>Complaint_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ComplaintItem__c/fields/RefundType__c.field-meta.xml
<CustomField>
    <fullName>RefundType__c</fullName>
    <label>Refund Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full</fullName>
            </value>
            <value>
                <fullName>Partial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ComplaintItem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ComplaintItemCompleted__e/ComplaintItemCompleted__e.object-meta.xml
<CustomObject>
    <label>Complaint Item Completed</label>
    <pluralLabel>Complaint Items Completed</pluralLabel>
</CustomObject>

force-app/main/default/objects/ComplaintItemCompleted__e/fields/ComplaintItems__c.field-meta.xml
<CustomField>
    <fullName>ComplaintItems__c</fullName>
    <label>Complaint Items</label>
    <length>65536</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ProductComplaint/triggers/ComplaintItemsCompleted_UpdateInternal.cls
public with sharing class ComplaintItemsCompleted_UpdateInternal implements TriggerAction.AfterInsert {
    public void afterInsert(List<ComplaintItemCompleted__e> newList){
        List<ComplaintBody> complaints = new List<ComplaintBody>();
        Set<String> externalProductIds = new Set<String>();
        Set<String> caseIds = new Set<String>();
        for (ComplaintItemCompleted__e event : newList) {
            try {
                List<ComplaintBody> eventComplaints = (List<ComplaintBody>) JSON.deserialize(event.ComplaintItems__c, List<ComplaintBody>.class);
                for(ComplaintBody complaint : eventComplaints){
                    if(complaint.ProductId != null){
                        externalProductIds.add(complaint.ProductId);
                    }
                    if(complaint.CaseId != null){
                        caseIds.add(complaint.CaseId);
                    }
                }
                complaints.addAll(eventComplaints);
            } catch (Exception e) {
                System.debug('Error deserializing event data: ' + e.getMessage());
            }
        }

        List<Product2> products = [
            SELECT Id, ExternalId__c
            FROM Product2 
            WHERE ExternalId__c IN :externalProductIds
        ];

        Map<String, Product2> externalIdToProduct = new Map<String, Product2>();
        for(Product2 product : products){
            externalIdToProduct.put(product.ExternalId__c, product);
        }
        
        List<ComplaintItem__c> complaintItemsToUpdate = [
            SELECT Id, Status__c, Product__c, Case__c, RefundAmount__c, RefundType__c
            FROM ComplaintItem__c
            WHERE Product__c IN :products AND Case__c IN :caseIds
        ];

        Map<Id, Map<Id, ComplaintItem__c>> caseIdToProductIdToComplaintItem = new Map<Id, Map<Id, ComplaintItem__c>>();
        for(ComplaintItem__c item : complaintItemsToUpdate){
            if(!caseIdToProductIdToComplaintItem.containsKey(item.Case__c)){
                caseIdToProductIdToComplaintItem.put(item.Case__c, new Map<Id, ComplaintItem__c>());
            }
            caseIdToProductIdToComplaintItem.get(item.Case__c).put(item.Product__c, item);
        }
        
        List<ComplaintItem__c> itemsToUpdate = new List<ComplaintItem__c>();
        for(ComplaintBody complaint : complaints){
            if(complaint.CaseId != null && complaint.ProductId != null && externalIdToProduct.containsKey(complaint.ProductId)){
                Product2 product = externalIdToProduct.get(complaint.ProductId);
                if(caseIdToProductIdToComplaintItem.containsKey(complaint.CaseId) && caseIdToProductIdToComplaintItem.get(complaint.CaseId).containsKey(product.Id)){
                    ComplaintItem__c itemToUpdate = caseIdToProductIdToComplaintItem.get(complaint.CaseId).get(product.Id);
                    itemToUpdate.Status__c = complaint.Status;
                    itemToUpdate.RefundType__c = complaint.RefundType;
                    itemToUpdate.RefundAmount__c = complaint.RefundAmount;
                    itemsToUpdate.add(itemToUpdate);
                }
            }
        }
        if(!itemsToUpdate.isEmpty()){
            List<Database.SaveResult> saveResults = Database.update(itemsToUpdate, false);
            for(Database.SaveResult saveResult : saveResults){
                if(!saveResult.isSuccess()){
                    System.debug('Error updating complaint item: ' + saveResult.getErrors());
                }
            }
        }

    }

    private class ComplaintBody{
        String CaseId;
        String ProductId;
        String Status;
        String RefundType;
        Decimal RefundAmount;
    }
}