force-app/main/default/objects/ComplaintItem__c/ComplaintItem__c.object-meta.xml
<CustomObject>
    <label>Complaint Item</label>
    <nameField>
        <label>Complaint Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Complaint Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ComplaintItem__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Complaint Items</relationshipLabel>
    <relationshipName>Complaint_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ComplaintItem__c/fields/IsExternalProduct__c.field-meta.xml
<CustomField>
    <fullName>IsExternalProduct__c</fullName>
    <defaultValue>false</defaultValue>
    <label>External Product</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ComplaintItem__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Complaint Items</relationshipLabel>
    <relationshipName>Complaint_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ComplaintItem__c/fields/OrderProduct__c.field-meta.xml
<CustomField>
    <fullName>OrderProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Complaint Items</relationshipLabel>
    <relationshipName>Complaint_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ComplaintItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Complaint Items</relationshipLabel>
    <relationshipName>Complaint_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ComplaintItem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/IsExternal__c.field-meta.xml
<CustomField>
    <fullName>IsExternal__c</fullName>
    <formula>NOT(ISBLANK(ExternalId__c))</formula>
    <label>External</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ProductComplaint/ProductComplaintService.cls
public with sharing class ProductComplaintService {
    public static List<Product2> getProducts(String orderId) {
        List<OrderItem> orderProducts = [SELECT Product2Id FROM OrderItem WHERE OrderId = :orderId];
        List<Id> productIds = new List<Id>();
        for (OrderItem orderProduct : orderProducts) {
            productIds.add(orderProduct.Product2Id);
        }
        
        return [SELECT Name, ProductCode, Family, IsExternal__c FROM Product2 WHERE Id IN :productIds];
    }

    public static ProductComplaintController.ComplaintResult submitComplaints(List<Id> productIds, String orderId) {
        Map<Id, Product2> products = new Map<Id, Product2>([
            SELECT Id, IsExternal__c, ExternalId__c
            FROM Product2
            WHERE Id IN :productIds
        ]);

        Map<Id, OrderItem> orderItems = new Map<Id, OrderItem>([
            SELECT Id, Product2Id, Quantity, UnitPrice
            FROM OrderItem
            WHERE OrderId = :orderId AND Product2Id IN :productIds AND UnitPrice > 0
        ]);

        ExternalEventBody eventBody = new ExternalEventBody();
        eventBody.externalIds = new List<Id>();
        eventBody.quantities = new List<Decimal>();
        eventBody.prices = new List<Decimal>();
        for (OrderItem orderItem : orderItems.values()) {
            Product2 product = products.get(orderItem.Product2Id);
            if (product.IsExternal__c) {
                eventBody.externalIds.add(product.ExternalId__c);
                eventBody.quantities.add(orderItem.Quantity);
                eventBody.prices.add(orderItem.UnitPrice);
            }
        }

        Id caseId = createApprovalProcesses(orderItems, products, orderId);
        eventBody.trackingId = caseId;

        ProductComplaintController.ComplaintResult result = new ProductComplaintController.ComplaintResult();
        result.status = 'PENDING';
        result.trackingId = caseId;

        if (!eventBody.externalIds.isEmpty()) {
            try {
                sendExternalEvent(eventBody);
            } catch (Exception e) {
                throw newAuraException(System.Label.externalComplaintSendingError);
            }
        } else {
            result.status = 'SUCCESS';
        }

        return result;
    }

    private static Id createApprovalProcesses(Map<Id, OrderItem> orderProducts, Map<Id, Product2> products, String orderId) {
        List<ComplaintItem__c> existingComplaintItems = [
            SELECT Id
            FROM ComplaintItem__c
            WHERE OrderProduct__c IN :orderProducts.keySet()
        ];
        if (!existingComplaintItems.isEmpty()) {
            throw newAuraException(System.Label.duplicateComplaintError);
        }

        Case newCase = new Case(
            Subject = 'Product complaint',
            Status = Constants.CaseConstants.Status.NEW_STATUS,
            Origin = Constants.CaseConstants.Origin.INTERNAL,
            Order__c = orderId
        );
        insert newCase;
        
        List<ComplaintItem__c> complaintItems = new List<ComplaintItem__c>();
        for (OrderItem orderProduct : orderProducts.values()) {
            ComplaintItem__c newComplaintItem = new ComplaintItem__c(
                Product__c = orderProduct.Product2Id,
                Case__c = newCase.Id,
                Order__c = orderId,
                IsExternalProduct__c = products.get(orderProduct.Product2Id).IsExternal__c,
                OrderProduct__c = orderProduct.Id,
                Quantity__c = orderProduct.Quantity,
                UnitPrice__c = orderProduct.UnitPrice
            );
            complaintItems.add(newComplaintItem);
        }
        insert complaintItems;

        List<ComplaintItem__c> internalComplaintItems = new List<ComplaintItem__c>();
        for (ComplaintItem__c complaintItem : complaintItems) {
            if (!complaintItem.IsExternalProduct__c) {
                internalComplaintItems.add(complaintItem);
            }
        }

        for (ComplaintItem__c complaintItem : internalComplaintItems) {
            Map<String, String> params = new Map<String, String>();
            params.put('recordId', complaintItem.Id);
            params.put('submitter', UserInfo.getUserId());
            Flow.Interview.Order_Item_Complaint flow = new Flow.Interview.Order_Item_Complaint(params);
            try {
                flow.start();
            } catch (Exception ex) {
                throw newAuraException(System.Label.approvalProcessCreationError);
            }
        }

        return newCase.Id;
    }

    private static void sendExternalEvent(ExternalEventBody eventBody) {
        System.enqueueJob(new AsyncSendExternalEvent(eventBody));
    }

    public class AsyncSendExternalEvent implements Queueable, Database.AllowsCallouts {
        private ExternalEventBody eventBody;

        public AsyncSendExternalEvent(ExternalEventBody eventBody) {
            this.eventBody = eventBody;
        }

        public void execute(QueueableContext context) {
            Map<String, String> event = new Map<String, String>();
            event.put('CaseId__c', eventBody.trackingId);
            event.put('ProductIds__c', JSON.serialize(eventBody.externalIds));
            event.put('Quantities__c', JSON.serialize(eventBody.quantities));
            event.put('Prices__c', JSON.serialize(eventBody.prices));

            HttpRequest req = new HttpRequest();
            req.setEndpoint(Constants.EXTERNAL_COMPLAINT_EVENT_API_ENDPOINT);
            req.setMethod(Constants.RestAPI.Method.POST);
            req.setHeader('Content-Type', 'application/json');

            try {
                req.setBody(JSON.serialize(event));

                Http http = new Http();
                HttpResponse res = http.send(req);
                
                if (res.getStatusCode() != 201) {
                    updateComplaintsOnError(eventBody.trackingId, eventBody.externalIds);
                }
            } catch (Exception e) {
                updateComplaintsOnError(eventBody.trackingId, eventBody.externalIds);
                throw e;
            }
        }
    }

    private static void updateComplaintsOnError(Id caseId, List<Id> externalProductIds) {
        List<Product2> products = [
            SELECT Id
            FROM Product2
            WHERE ExternalId__c IN :externalProductIds
        ];
        List<ComplaintItem__c> complaintItems = [
            SELECT Id, Status__c
            FROM ComplaintItem__c
            WHERE Case__c = :caseId AND Product__c IN :products
        ];
        for (ComplaintItem__c complaintItem : complaintItems) {
            complaintItem.Status__c = Constants.ComplaintItem.Status.ERROR;
        }
        update complaintItems;
    }

    private class ExternalEventBody {
        public String trackingId;
        public List<Id> externalIds;
        public List<Decimal> quantities;
        public List<Decimal> prices;
    }

    private static AuraHandledException newAuraException(String message) {
        AuraHandledException e = new AuraHandledException(message);
        e.setMessage(message);
        return e;
    }
}