force-app/main/default/objects/RequestLog__c/RequestLog__c.object-meta.xml
<CustomObject>
    <label>Request Log</label>
    <nameField>
        <displayFormat>R-{00000}</displayFormat>
        <label>Request Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Request Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RequestLog__c/fields/AttemptNumber__c.field-meta.xml
<CustomField>
    <fullName>AttemptNumber__c</fullName>
    <label>Attempt Number</label>
    <precision>1</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RequestLog__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Reattempted</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Utils/Builders/Tests/BaseRequestLogTestDataBuilder.cls
public virtual class BaseRequestLogTestDataBuilder extends TestDataBuilder {
    public BaseRequestLogTestDataBuilder() {
         record = new RequestLog__c();
    }

    protected override void prepare() {
        RequestLog__c requestLog = (RequestLog__c) record;
        if (String.isBlank(requestLog.Status__c)) {
            requestLog.Status__c = Constants.RequestLog.Status.SUCCESS;
        }
        if (requestLog.AttemptNumber__c == null) {
            requestLog.AttemptNumber__c = 1;
        }
    }
}