force-app/main/default/objects/RequestLog__c/RequestLog__c.object-meta.xml
<CustomObject>
    <label>Request Log</label>
    <nameField>
        <displayFormat>R-{00000}</displayFormat>
        <label>Request Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Request Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RequestLog__c/fields/AttemptNumber__c.field-meta.xml
<CustomField>
    <fullName>AttemptNumber__c</fullName>
    <label>Attempt Number</label>
    <precision>1</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RequestLog__c/fields/SourceLog__c.field-meta.xml
<CustomField>
    <fullName>SourceLog__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Source Log</label>
    <referenceTo>RequestLog__c</referenceTo>
    <relationshipLabel>Related Request Logs</relationshipLabel>
    <relationshipName>RelatedRequestLogs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RequestLog__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Reattempted</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RequestProduct__c/RequestProduct__c.object-meta.xml
<CustomObject>
    <label>Request Product</label>
    <nameField>
        <label>Request Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Request Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RequestProduct__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Request Products</relationshipLabel>
    <relationshipName>Request_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RequestProduct__c/fields/RequestLog__c.field-meta.xml
<CustomField>
    <fullName>RequestLog__c</fullName>
    <label>Request Log</label>
    <referenceTo>RequestLog__c</referenceTo>
    <relationshipLabel>Request Products</relationshipLabel>
    <relationshipName>Request_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ProductSync/ScheduledSyncFailedRequest.cls
public class ScheduledSyncFailedRequest implements Schedulable {
    public void execute( SchedulableContext context ) {
        Integer maxAttemptNumber = (Integer)Constants.REQUEST_LOG_SETTING.MaxAttemptNumber__c;
        List<RequestLog__c> failedRequests = [
            SELECT Id, AttemptNumber__c, Status__c
            FROM RequestLog__c
            WHERE Status__c = :Constants.RequestLog.Status.FAILED
            AND AttemptNumber__c < :maxAttemptNumber
        ];

        List<RequestLog__c> newRequests = new List<RequestLog__c>();
        for (RequestLog__c failedRequest : failedRequests) {
            RequestLog__c newRequest = new RequestLog__c(
                Status__c = Constants.RequestLog.Status.PENDING,
                AttemptNumber__c = failedRequest.AttemptNumber__c + 1,
                SourceLog__c = failedRequest.Id
            );   
            newRequests.add(newRequest);
        }

        List<RequestProduct__c> oldRequestProducts = [
            SELECT Id, Product__c, RequestLog__c 
            FROM RequestProduct__c 
            WHERE RequestLog__c IN :failedRequests
        ];
        Map<Id, List<RequestProduct__c>> oldRequestToRequestProduct = new Map<Id, List<RequestProduct__c>>();
        for (RequestProduct__c requestProduct : oldRequestProducts) {
            if (!oldRequestToRequestProduct.containsKey(requestProduct.RequestLog__c)) {
                oldRequestToRequestProduct.put(requestProduct.RequestLog__c, new List<RequestProduct__c>());
            }
            oldRequestToRequestProduct.get(requestProduct.RequestLog__c).add(requestProduct);
        }

        insert newRequests;

        List<RequestProduct__c> newRequestProducts = new List<RequestProduct__c>();
        for (RequestLog__c request : newRequests) {
            for (RequestProduct__c requestProduct : oldRequestToRequestProduct.get(request.SourceLog__c)) {
                RequestProduct__c newRequestProduct = new RequestProduct__c(
                    RequestLog__c = request.Id,
                    Product__c = requestProduct.Product__c
                );
                newRequestProducts.add(newRequestProduct);
            }
        }
        insert newRequestProducts;

        if (!Test.isRunningTest()) {
            if (!BatchStatusTracker.isBatchRunning(BatchSyncFailedRequest.class.getName())) {
                Database.executeBatch(new BatchSyncFailedRequest(), (Integer)Constants.REQUEST_LOG_SETTING.MaxRequestsPerBatch__c);
            }
        } else {
            Database.executeBatch(new BatchSyncFailedRequest(), 2000);
        }
    }
}