force-app/main/default/objects/RequestLog__c/RequestLog__c.object-meta.xml
<CustomObject>
    <label>Request Log</label>
    <nameField>
        <displayFormat>R-{00000}</displayFormat>
        <label>Request Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Request Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RequestLog__c/fields/AttemptNumber__c.field-meta.xml
<CustomField>
    <fullName>AttemptNumber__c</fullName>
    <label>Attempt Number</label>
    <precision>1</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RequestLog__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Reattempted</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProductSync/tests/Product_SendInsertedToExternalTest.cls
@isTest
private class Product_SendInsertedToExternalTest {

    @isTest
    static void testSendBigDataChunk() {
        Test.setMock(HttpCalloutMock.class, new MockProductSyncREST());

        Integer productCount = 10000;
        List<Product2> productsToSend = new List<Product2>();
        for (Integer i = 0; i < productCount; i++) {
            productsToSend.add((Product2) new BaseProductTestDataBuilder().create());
        }
        Test.startTest();
        insert productsToSend;
        Test.stopTest();

        Integer expectedSize = productCount / Constants.RequestLog.MAX_PRODUCTS_PER_REQUEST;
        List<RequestLog__c> requestLogs = [SELECT Id, Status__c, AttemptNumber__c FROM RequestLog__c];
        Assert.areEqual(expectedSize, requestLogs.size());
    }
}