force-app/main/default/objects/RequestLog__c/RequestLog__c.object-meta.xml
<CustomObject>
    <label>Request Log</label>
    <nameField>
        <displayFormat>R-{00000}</displayFormat>
        <label>Request Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Request Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RequestLog__c/fields/AttemptNumber__c.field-meta.xml
<CustomField>
    <fullName>AttemptNumber__c</fullName>
    <label>Attempt Number</label>
    <precision>1</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RequestLog__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Reattempted</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RequestProduct__c/RequestProduct__c.object-meta.xml
<CustomObject>
    <label>Request Product</label>
    <nameField>
        <label>Request Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Request Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RequestProduct__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Request Products</relationshipLabel>
    <relationshipName>Request_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RequestProduct__c/fields/RequestLog__c.field-meta.xml
<CustomField>
    <fullName>RequestLog__c</fullName>
    <label>Request Log</label>
    <referenceTo>RequestLog__c</referenceTo>
    <relationshipLabel>Request Products</relationshipLabel>
    <relationshipName>Request_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ProductSync/triggers/ProductSendToExternalHelper.cls
public class ProductSendToExternalHelper {
    public static void createPendingRequests(List<Product2> newList) {
        List<Product2> productGroup = new List<Product2>();
        Integer asyncBatchSize = System.Limits.getLimitDmlRows() / 2;

        for (Product2 product : newList){
            productGroup.add(product);
            if (productGroup.size() == asyncBatchSize) {
                AsyncCreateRequest asyncCreateRequest = new AsyncCreateRequest(productGroup);
                System.enqueueJob(asyncCreateRequest);
            }
        }
        if (!productGroup.isEmpty()) {
            AsyncCreateRequest asyncCreateRequest = new AsyncCreateRequest(productGroup);
            System.enqueueJob(asyncCreateRequest);
        }
    }

    private class AsyncCreateRequest implements Queueable {
        private List<Product2> newList;
        public AsyncCreateRequest(List<Product2> newList) {
            this.newList = newList;
        }

        public void execute(QueueableContext context) {
            List<Product2> productGroup = new List<Product2>();
            List<RequestItem> requestItems = new List<RequestItem>();
            List<RequestLog__c>  requestLogsToInsert = new List<RequestLog__c>();
            Integer batchSize = (Integer) Constants.REQUEST_LOG_SETTING.MaxProductsPerRequest__c;
            String requestStatus = Constants.RequestLog.Status.PENDING;

            for(Product2 product : newList){
                productGroup.add(product);
                if (productGroup.size() == batchSize) {
                    RequestItem requestItem = new RequestItem(productGroup, requestStatus);
                    requestItems.add(requestItem);
                    requestLogsToInsert.add(requestItem.requestLog);
                    productGroup.clear();
                }
            }
            if (!productGroup.isEmpty()) {
                RequestItem requestItem = new RequestItem(productGroup, requestStatus);
                requestItems.add(requestItem);
                requestLogsToInsert.add(requestItem.requestLog);
            }
            insert requestLogsToInsert;

            List<RequestProduct__c> requestProductsToInsert = new List<RequestProduct__c>();
            for (RequestItem requestItem : requestItems) {
                for (Product2 product : requestItem.products) {
                    RequestProduct__c requestProduct = new RequestProduct__c(
                        RequestLog__c = requestItem.requestLog.Id,
                        Product__c = product.Id
                    );
                    requestProductsToInsert.add(requestProduct);
                }
            }
            insert requestProductsToInsert;

            Integer requestsPerBatch = (Integer)Constants.REQUEST_LOG_SETTING.MaxRequestsPerBatch__c;
            if (Test.isRunningTest()) {
                requestsPerBatch = 2000;
            }

            if (!BatchStatusTracker.isBatchRunning(BatchSyncFailedRequest.class.getName())) {
                Database.executeBatch(new BatchSyncFailedRequest(), requestsPerBatch);
            }
        }
    }

    private class RequestItem {
        public RequestLog__c requestLog { get; set; }
        public List<Product2> products { get; set; }

        public RequestItem(List<Product2> products, String status) {
            this.products = products;
            this.requestLog = new RequestLog__c(Status__c = status, AttemptNumber__c = 1);
        }
    }
}