force-app/main/default/objects/RequestLog__c/RequestLog__c.object-meta.xml
<CustomObject>
    <label>Request Log</label>
    <nameField>
        <displayFormat>R-{00000}</displayFormat>
        <label>Request Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Request Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RequestLog__c/fields/AttemptNumber__c.field-meta.xml
<CustomField>
    <fullName>AttemptNumber__c</fullName>
    <label>Attempt Number</label>
    <precision>1</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RequestLog__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Reattempted</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProductSync/tests/AsyncSendProductToExternalTest.cls
@isTest
private class AsyncSendProductToExternalTest {

    @isTest
    static void testSendNewDataToExternal() {
        Test.setMock(HttpCalloutMock.class, new MockProductSyncREST());

        List<Product2> productsToSend = new ProductTestDataFactory().buildData(3, new BaseProductTestDataBuilder());

        AsyncSendProductsToExternal job = new AsyncSendProductsToExternal(productsToSend, Constants.RestAPI.Method.POST);
        Test.startTest();
        System.enqueueJob(job);
        Test.stopTest();

        List<RequestLog__c> requestLogs = [SELECT Id, Status__c, AttemptNumber__c FROM RequestLog__c];
        Assert.areEqual(1, requestLogs.size(), 'Should be 1 RequestLog__c record');
        Assert.areEqual(Constants.RequestLog.Status.SUCCESS, requestLogs[0].Status__c, 'Request should succeed');
        Assert.areEqual(1, requestLogs[0].AttemptNumber__c, 'Should be 1 attempt');
    }
}