force-app/main/default/objects/RequestLog__c/RequestLog__c.object-meta.xml
<CustomObject>
    <label>Request Log</label>
    <nameField>
        <displayFormat>R-{00000}</displayFormat>
        <label>Request Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Request Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RequestProduct__c/RequestProduct__c.object-meta.xml
<CustomObject>
    <label>Request Product</label>
    <nameField>
        <label>Request Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Request Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RequestProduct__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Request Products</relationshipLabel>
    <relationshipName>Request_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RequestProduct__c/fields/RequestLog__c.field-meta.xml
<CustomField>
    <fullName>RequestLog__c</fullName>
    <label>Request Log</label>
    <referenceTo>RequestLog__c</referenceTo>
    <relationshipLabel>Request Products</relationshipLabel>
    <relationshipName>Request_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Utils/Builders/Tests/BaseRequestProductTestDataBuilder.cls
public virtual class BaseRequestProductTestDataBuilder extends TestDataBuilder {
    public BaseRequestProductTestDataBuilder() {
         record = new RequestProduct__c();
    }

    public BaseRequestProductTestDataBuilder withProduct(Product2 product) {
        RequestProduct__c requestProduct = (RequestProduct__c) record;
        requestProduct.Product__c = product.Id;
        return this;
    }

    public BaseRequestProductTestDataBuilder withRequest(RequestLog__c request) {
        RequestProduct__c requestProduct = (RequestProduct__c) record;
        requestProduct.RequestLog__c = request.Id;
        return this;
    }
}