force-app/main/default/objects/Discount__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <inlineHelpText>A fixed amount deducted from the price of the product</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Amount_Type__c.field-meta.xml
<CustomField>
    <fullName>Amount_Type__c</fullName>
    <inlineHelpText>How is the discount calculated</inlineHelpText>
    <label>Amount Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fixed_Amount</fullName>
                <label>Fixed Amount</label>
            </value>
            <value>
                <fullName>Percentage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Percentage__c.field-meta.xml
<CustomField>
    <fullName>Percentage__c</fullName>
    <inlineHelpText>Percentage deducted from the product price</inlineHelpText>
    <label>Percentage</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/Discounts/Strategies/BaseDiscountStrategy.cls
public abstract class BaseDiscountStrategy implements IDiscountStrategy {
    public abstract Boolean isApplicable(Discount__c discount, Decimal totalOrderAmount);
    
    public Decimal calculateDiscount(OrderItem item, Discount__c discount) {
        if (discount.Amount_Type__c == Constants.Discount.FIXED_AMOUNT_TYPE) {
            return discount.Amount__c * item.Quantity;
        } else if (discount.Amount_Type__c == Constants.Discount.PERCENTAGE_AMOUNT_TYPE) {
            Decimal price = item.UnitPrice * item.Quantity;
            return price * discount.Percentage__c / 100;
        } else {
            return 0;
        }
    }
}