force-app/main/default/objects/Discount__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <inlineHelpText>A fixed amount deducted from the price of the product</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Amount_Type__c.field-meta.xml
<CustomField>
    <fullName>Amount_Type__c</fullName>
    <inlineHelpText>How is the discount calculated</inlineHelpText>
    <label>Amount Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fixed_Amount</fullName>
                <label>Fixed Amount</label>
            </value>
            <value>
                <fullName>Percentage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Discount__c/fields/isActive__c.field-meta.xml
<CustomField>
    <fullName>isActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Percentage__c.field-meta.xml
<CustomField>
    <fullName>Percentage__c</fullName>
    <inlineHelpText>Percentage deducted from the product price</inlineHelpText>
    <label>Percentage</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Pricebook__c.field-meta.xml
<CustomField>
    <fullName>Pricebook__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Discounts</relationshipLabel>
    <relationshipName>Discounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Discounts</relationshipLabel>
    <relationshipName>Discounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Recurrence_Day_Of_Month__c.field-meta.xml
<CustomField>
    <fullName>Recurrence_Day_Of_Month__c</fullName>
    <label>Recurrence Day Of Month</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Recurrence_Month_Of_Year__c.field-meta.xml
<CustomField>
    <fullName>Recurrence_Month_Of_Year__c</fullName>
    <label>Recurrence Month Of Year</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Recurrence_Type__c.field-meta.xml
<CustomField>
    <fullName>Recurrence_Type__c</fullName>
    <label>Recurrence Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Recurring</fullName>
            </value>
            <value>
                <fullName>Timed</fullName>
            </value>
            <value>
                <fullName>Special</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Discounts/OrderItemsDiscountEvaluatorTest.cls
@isTest
private class OrderItemsDiscountEvaluatorTest {
    @testSetup
    static void setup(){
        Account acc = new Account(Name = 'Test Account');
        insert acc;

        Pricebook2 standardPricebook = new Pricebook2(Id = Test.getStandardPricebookId(), IsActive = true);
        update standardPricebook;

        List<Product2> products = TestDataFactory.ConstructProducts(5);
        insert products;

        List<PricebookEntry> pricebookEntries = TestDataFactory.ConstructPricebookEntries(products);
        insert pricebookEntries;

        Order order = new Order();
        order.Name = 'TestOrder';
        order.Status = 'Draft';
        order.AccountId = acc.Id;
        order.EffectiveDate = System.today();
        order.Pricebook2Id = standardPricebook.Id;
        insert order;

        List<OrderItem> orderItems = TestDataFactory.ConstructOrderItems(5, order, pricebookEntries);
        insert orderItems;
    }

    @isTest
    static void testEmptyOrderItemList() {
        List<OrderItem> orderItems = new List<OrderItem>();
        Id pricebookId = Test.getStandardPricebookId();
        Test.startTest();
        List<OrderItemsDiscountEvaluator.ItemDiscountResult> result = OrderItemsDiscountEvaluator.Evaluate(orderItems, pricebookId);
        Test.stopTest();
        System.Assert.areEqual(0, result.size());
    }

    @isTest
    static void testPercentageDiscount() {
        List<OrderItem> orderItems = [SELECT UnitPrice, Quantity, PricebookEntryId, Product2Id FROM OrderItem];

        Id pricebookId = Test.getStandardPricebookId();

        List<Discount__c> timedDiscounts = CreateTestTimedDiscounts(true, 'Percentage', 5, 5);
        insert timedDiscounts;
        timedDiscounts = CreateTestTimedDiscounts(false, 'Percentage', 5, 5);
        insert timedDiscounts;

        Test.startTest();
        List<OrderItemsDiscountEvaluator.ItemDiscountResult> result = OrderItemsDiscountEvaluator.Evaluate(orderItems, pricebookId);
        Test.stopTest();

        List<ItemDiscountEvaluator.EvaluatedDiscount> appliedDiscounts = new List<ItemDiscountEvaluator.EvaluatedDiscount>();
        Decimal totalDiscount = 0;
        for (OrderItemsDiscountEvaluator.ItemDiscountResult resultItem : result) {
            for (ItemDiscountEvaluator.EvaluatedDiscount appliedDiscount : resultItem.appliedDiscounts) {
                appliedDiscounts.add(appliedDiscount);
            }
            totalDiscount += resultItem.totalDiscount;
        }
        System.assertEquals(5, appliedDiscounts.size());
        System.assertEquals(2.5, totalDiscount);
    }

    @isTest
    static void testInvalidTimedDiscount() {
        List<OrderItem> orderItems = [SELECT UnitPrice, Quantity, PricebookEntryId, Product2Id FROM OrderItem];

        Id pricebookId = Test.getStandardPricebookId();
        List<Discount__c> timedDiscounts = CreateTestTimedDiscounts(false, 'Percentage', 5, 5);
        insert timedDiscounts;

        Test.startTest();
        List<OrderItemsDiscountEvaluator.ItemDiscountResult> result = OrderItemsDiscountEvaluator.Evaluate(orderItems, pricebookId);
        Test.stopTest();

        List<ItemDiscountEvaluator.EvaluatedDiscount> appliedDiscounts = new List<ItemDiscountEvaluator.EvaluatedDiscount>();
        Decimal totalDiscount = 0;
        for (OrderItemsDiscountEvaluator.ItemDiscountResult resultItem : result) {
            for (ItemDiscountEvaluator.EvaluatedDiscount appliedDiscount : resultItem.appliedDiscounts) {
                appliedDiscounts.add(appliedDiscount);
            }
            totalDiscount += resultItem.totalDiscount;
        }
        System.assertEquals(0, appliedDiscounts.size());
        System.assertEquals(0, totalDiscount);
    }

    private static List<Discount__c> CreateTestTimedDiscounts(Boolean valid, String amountType, Decimal value, Integer cnt) {
        List<Product2> products = [SELECT Id FROM Product2];
        
        Id pricebookId = Constants.STANDARD_PRICEBOOK_ID;
        Date startDate = Date.today().addDays(-2);
        Date endDate = Date.today().addDays(2);
        if (!valid) {
            startDate = Date.today().addDays(2);
            endDate = Date.today().addDays(5);
        }

        List<Discount__c> discounts = new List<Discount__c>();
        for (Integer i = 0; i < cnt; i++) {
            Discount__c discount = new Discount__c();
            discount.Pricebook__c = pricebookId;
            discount.Product__c = products[Math.mod(i, products.size())].Id;
            discount.Type__c = 'Timed';
            discount.Start_Date__c = startDate;
            discount.End_Date__c = endDate;
            discount.Name = 'Test';
            discount.Amount_Type__c = amountType;
            if (amountType == 'Percentage') {
                discount.Percentage__c = value;
            } else {
                discount.Amount__c = value;
            }
            discount.isActive__c = true;
            discounts.add(discount);
        }
        return discounts;
    }

    private static List<Discount__c> CreateTestRecuringDiscounts(Boolean valid, String amountType, Decimal value, String recurrenceType, Integer cnt) {
        List<Product2> products = [SELECT Id FROM Product2];
        Id pricebookId = Test.getStandardPricebookId();
        Date startDate = Date.today();
        if (!valid) {
            startDate = Date.today().addDays(2);
        }

        List<Discount__c> discounts = new List<Discount__c>();
        for (Integer i = 0; i < cnt; i++) {
            Discount__c discount = new Discount__c();
            discount.Pricebook__c = pricebookId;
            discount.Product__c = products[Math.mod(i, products.size())].Id;
            discount.Type__c = 'Recurring';
            discount.Recurrence_Type__c = recurrenceType;
            discount.Recurrence_Day_Of_Month__c = String.valueOf(startDate.day());
            discount.Recurrence_Month_Of_Year__c = String.valueOf(startDate.month());
            discount.Name = 'Test';
            discount.Amount_Type__c = amountType;
            discount.Percentage__c = value;
            discount.isActive__c = true;
            discounts.add(discount);
        }
        return discounts;
    }
}