force-app/main/default/objects/Discount__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <inlineHelpText>A fixed amount deducted from the price of the product</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Amount_Type__c.field-meta.xml
<CustomField>
    <fullName>Amount_Type__c</fullName>
    <inlineHelpText>How is the discount calculated</inlineHelpText>
    <label>Amount Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fixed_Amount</fullName>
                <label>Fixed Amount</label>
            </value>
            <value>
                <fullName>Percentage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Threshold_Amount__c.field-meta.xml
<CustomField>
    <fullName>Threshold_Amount__c</fullName>
    <inlineHelpText>The total value that an order must reach to qualify for a special discount</inlineHelpText>
    <label>Threshold Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Recurring</fullName>
            </value>
            <value>
                <fullName>Timed</fullName>
            </value>
            <value>
                <fullName>Special</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Discounts/tests/DiscountControllerTest.cls
@isTest
private class DiscountControllerTest {

    @isTest
    static void testDiscountRecordCount() {
        createTestDiscounts();
        Test.startTest();
        Integer result = DiscountController.getRecordCount();
        Test.stopTest();
        System.assertEquals(30, result);
    }

    @isTest
    static void testGetDiscountRecords() {
        createTestDiscounts();
        Test.startTest();
        List<Discount__c> result = DiscountController.getRecordList(30, 0);
        Test.stopTest();
        System.assertEquals(30, result.size());
    }

    @isTest
    static void testGetDiscountRecordsWithNullRecordPerPage() {
        createTestDiscounts();
        Test.startTest();
        List<Discount__c> result = DiscountController.getRecordList(null, 0);
        Test.stopTest();
        System.assertEquals(10, result.size());
    }

    @isTest
    static void testGetDiscountRecordsWithNullOffset() {
        createTestDiscounts();
        Test.startTest();
        List<Discount__c> result = DiscountController.getRecordList(20, null);
        Test.stopTest();
        System.assertEquals(20, result.size());
    }

    @isTest
    static void testGetDiscountRecordsWithNoRecords() {
        Test.startTest();
        List<Discount__c> result = DiscountController.getRecordList(20, 0);
        Test.stopTest();
        System.assertEquals(0, result.size());
    }

    @isTest
    static void testGetDiscountRecordsWithOffset() {
        createTestDiscounts();
        Test.startTest();
        List<Discount__c> result = DiscountController.getRecordList(30, 10);
        Test.stopTest();
        System.assertEquals(20, result.size());
    }

    private static void createTestDiscounts() {
        List<Discount__c> discounts = new List<Discount__c>();
        for (Integer i = 0; i < 30; i++) {
            discounts.add((Discount__c) new DiscountTestDataBuilder().create());
        }
        insert discounts;
    }

    private class DiscountTestDataBuilder extends BaseDiscountTestDataBuilder {
        protected override void prepare(){
            super.prepare();
            Discount__c discount = (Discount__c) record;
            discount.Type__c = Constants.Discount.Type.SPECIAL;
            discount.Threshold_Amount__c = 100;
            discount.Amount_Type__c = Constants.Discount.AmountType.FIXED;
            discount.Amount__c = 10;
        }
    }
}