force-app/main/default/objects/Discount__c/fields/isActive__c.field-meta.xml
<CustomField>
    <fullName>isActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Pricebook__c.field-meta.xml
<CustomField>
    <fullName>Pricebook__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Discounts</relationshipLabel>
    <relationshipName>Discounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Discounts</relationshipLabel>
    <relationshipName>Discounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Discounts/DiscountService.cls
public  class DiscountService {
    public static Integer getRecordCount(){
        Integer totalCount = [SELECT COUNT() FROM Discount__c];
        return totalCount;
    }

    public static List<Discount__c> getRecordList(Integer recordsPerPage, Integer offset){
        if (recordsPerPage == null || recordsPerPage < 1) {
            recordsPerPage = 10;
        }
        if (offset == null || offset < 0) {
            offset = 0;
        }

        QueryBuilder query = new QueryBuilder(Discount__c.sObjectType)
            .addField(Discount__c.Name)
            .addField(Discount__c.Product__c, Product2.Name)
            .addField(Discount__c.Pricebook__c, Pricebook2.Name)
            .addField(Discount__c.isActive__c)
            .setLimit(recordsPerPage)
            .setOffset(offset);
        List<Discount__c> discounts = Database.query(query.toString());
        return discounts;
    }
}