force-app/main/default/objects/Discount__c/fields/Recurrence_Day_Of_Month__c.field-meta.xml
<CustomField>
    <fullName>Recurrence_Day_Of_Month__c</fullName>
    <label>Recurrence Day Of Month</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Recurrence_Month_Of_Year__c.field-meta.xml
<CustomField>
    <fullName>Recurrence_Month_Of_Year__c</fullName>
    <label>Recurrence Month Of Year</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Discount__c/fields/Recurrence_Type__c.field-meta.xml
<CustomField>
    <fullName>Recurrence_Type__c</fullName>
    <label>Recurrence Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Discounts/Strategies/RecurringDiscountStrategy.cls
public class RecurringDiscountStrategy extends BaseDiscountStrategy {
    private static final String PREFIX = RecurringDiscountStrategy.class.getName().split(':')[0];

    public override Boolean isApplicable(Discount__c discount, Decimal totalOrderAmount) {
        Date today = Date.today();

        try{
            RecurrenceType recurrenceType = (RecurrenceType)Type.forName(PREFIX + '.' + discount.Recurrence_Type__c).newInstance();
            return recurrenceType.isApplicable(discount, totalOrderAmount);
        } catch (Exception e) {
            throw new DiscountException(System.Label.Unsuported_Recurrence_Type + discount.Recurrence_Type__c);
        }
    }

    public interface RecurrenceType {
        Boolean isApplicable(Discount__c discount, Decimal totalOrderAmount);
    }

    public class Monthly implements RecurrenceType {
        public Boolean isApplicable(Discount__c discount, Decimal totalOrderAmount) {
            return Date.today().day() == Integer.valueOf(discount.Recurrence_Day_Of_Month__c);
        }
    }

    public class Yearly implements RecurrenceType {
        public Boolean isApplicable(Discount__c discount, Decimal totalOrderAmount) {
            Date today = Date.today();
            return today.day() == Integer.valueOf(discount.Recurrence_Day_Of_Month__c) &&
                today.month() == Integer.valueOf(discount.Recurrence_Month_Of_Year__c);
        }
    }
}