force-app/main/default/objects/Discount__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Recurring</fullName>
            </value>
            <value>
                <fullName>Timed</fullName>
            </value>
            <value>
                <fullName>Special</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Discounts/Strategies/DiscountStrategyFactory.cls
public class DiscountStrategyFactory {
    public static IDiscountStrategy getStrategy(Discount__c discount) {
        switch on discount.Type__c {
            when 'Recurring' {
                return new RecurringDiscountStrategy();
            }
            when 'Timed' {
                return new TimedDiscountStrategy();
            }
            when 'Special' {
                return new SpecialDiscountStrategy();
            }
            when else {
                throw new DiscountException('Unsupported discount type: ' + discount.Type__c);
            }
        }
    }
}